module.exports = {
  token: 'required',
  sellerEmail: 'required',
  extraAmount: 'required',
  itens: 'required',
  notificationUrl: 'required',
  reference: 'required',
  buyerName: 'required',
  buyerCPF: 'required',
  buyerAreaCode: 'required',
  buyerPhone: 'required',
  buyerEmail: 'required',
  senderHash: 'required',
  // shippingAddressStreet:'required',
  // shippingAddressNumber:'required',
  // shippingAddressComplement:'required',
  // shippingAddressDistrict:'required',
  // shippingAddressPostalCode:'required',
  // shippingAddressCity:'required',
  // shippingAddressState:'required',
  // shippingAddressCountry:'required',
  // shippingType:'required',
  // shippingCost:'required',
  bankName: 'required'
}
